@doc raw"""
    SamplerAttribute

Abstract supertype for optimizer attributes declared by QUBODrivers samplers.

Attributes generated by [`QUBODrivers.@setup`](@ref), such as
`NumberOfReads`, subtype `SamplerAttribute` and can be used with `MOI.get`,
`MOI.set`, and `MOI.supports`.
"""
abstract type SamplerAttribute <: MOI.AbstractOptimizerAttribute end

@doc raw"""
    RawSamplerAttribute{key}

QUBODrivers raw optimizer attribute identified by a string-like key.

`RawSamplerAttribute("num_reads")` is the QUBODrivers counterpart of
`MOI.RawOptimizerAttribute("num_reads")`. Generated samplers route MOI raw
attributes through this type so solver-specific attributes can share the same
storage and validation as typed sampler attributes.
"""
struct RawSamplerAttribute{key} <: SamplerAttribute
    RawSamplerAttribute{key}() where {key} = new{key}()
end

RawSamplerAttribute(key::String) = RawSamplerAttribute{Symbol(key)}()

@doc raw"""
    @raw_attr_str("key")

Create a `RawSamplerAttribute` type for dispatch.

This macro is useful when extending validation for a particular raw attribute:

```julia
function MOI.set(sampler::Optimizer, attr::QUBODrivers.@raw_attr_str("seed"), value)
    QUBODrivers.set_raw_attr!(sampler, attr, value)
    return nothing
end
```
"""
macro raw_attr_str(key::String)
    return :(RawSamplerAttribute{$(esc(QuoteNode(Symbol(key))))})
end

@doc raw"""
    default_raw_attr(sampler, attr)

Return the default value for a raw sampler attribute.

Methods are generated by [`QUBODrivers.@setup`](@ref) for declared attributes.
Sampler implementations may add methods to customize defaults for additional
raw attributes.
"""
function default_raw_attr end

@doc raw"""
    get_raw_attr(sampler, attr)

Return a raw sampler attribute value.

Generated optimizers first look in the sampler's attribute storage and then
fall back to [`default_raw_attr`](@ref). Most users access this through
`MOI.get(sampler, MOI.RawOptimizerAttribute(name))` or a typed attribute.
"""
function get_raw_attr end

@doc raw"""
    set_raw_attr!(sampler, attr, value)

Store a raw sampler attribute value.

Generated optimizers use this hook from `MOI.set`. Sampler implementations can
specialize it, or specialize `MOI.set` for a `RawSamplerAttribute`, to validate
backend-specific options before storing them.
"""
function set_raw_attr! end
