@doc raw"""
    SamplerAttribute

Abstract supertype for optimizer attributes declared by QUBODrivers samplers.

Attributes generated by [`QUBODrivers.@setup`](@ref), such as
`NumberOfReads`, subtype `SamplerAttribute` and can be used with `MOI.get`,
`MOI.set`, and `MOI.supports`.
"""
abstract type SamplerAttribute <: MOI.AbstractOptimizerAttribute end

@doc raw"""
    RawSamplerAttribute{key}

QUBODrivers raw optimizer attribute identified by a string-like key.

`RawSamplerAttribute("num_reads")` is the QUBODrivers counterpart of
`MOI.RawOptimizerAttribute("num_reads")`. Generated samplers route MOI raw
attributes through this type so solver-specific attributes can share the same
storage and validation as typed sampler attributes.
"""
struct RawSamplerAttribute{key} <: SamplerAttribute
    RawSamplerAttribute{key}() where {key} = new{key}()
end

RawSamplerAttribute(key::String) = RawSamplerAttribute{Symbol(key)}()

const _NUMBER_OF_READS_RAW       = "num_reads"
const _FINAL_NUMBER_OF_READS_RAW = "final_num_reads"

const _RawNumberOfReads      = RawSamplerAttribute{Symbol(_NUMBER_OF_READS_RAW)}
const _RawFinalNumberOfReads = RawSamplerAttribute{Symbol(_FINAL_NUMBER_OF_READS_RAW)}

@doc raw"""
    FinalNumberOfReads()

Generic sampler optimizer attribute for the number of reads used to build the
final emitted `SampleSet`.

`NumberOfReads` remains the convention for reads used by a sampler's internal
search, optimization, or objective evaluations. `FinalNumberOfReads` separates
the number of reads returned to users from those internal evaluations. If the
final read count is unset (`nothing`), the effective final read count defaults
to the sampler's raw `"num_reads"` attribute when that attribute is supported.

Generated optimizers created by [`QUBODrivers.@setup`](@ref) support this
attribute and the raw `"final_num_reads"` key.
"""
struct FinalNumberOfReads <: SamplerAttribute end

@doc raw"""
    @raw_attr_str("key")

Create a `RawSamplerAttribute` type for dispatch.

This macro is useful when extending validation for a particular raw attribute:

```julia
function MOI.set(sampler::Optimizer, attr::QUBODrivers.@raw_attr_str("seed"), value)
    QUBODrivers.set_raw_attr!(sampler, attr, value)
    return nothing
end
```
"""
macro raw_attr_str(key::String)
    return :(RawSamplerAttribute{$(esc(QuoteNode(Symbol(key))))})
end

@doc raw"""
    default_raw_attr(sampler, attr)

Return the default value for a raw sampler attribute.

Methods are generated by [`QUBODrivers.@setup`](@ref) for declared attributes.
Sampler implementations may add methods to customize defaults for additional
raw attributes.
"""
function default_raw_attr end

@doc raw"""
    get_raw_attr(sampler, attr)

Return a raw sampler attribute value.

Generated optimizers first look in the sampler's attribute storage and then
fall back to [`default_raw_attr`](@ref). Most users access this through
`MOI.get(sampler, MOI.RawOptimizerAttribute(name))` or a typed attribute.
"""
function get_raw_attr end

@doc raw"""
    set_raw_attr!(sampler, attr, value)

Store a raw sampler attribute value.

Generated optimizers use this hook from `MOI.set`. Sampler implementations can
specialize it, or specialize `MOI.set` for a `RawSamplerAttribute`, to validate
backend-specific options before storing them.
"""
function set_raw_attr! end

@doc raw"""
    final_number_of_reads(sampler)

Return the effective final read count for `sampler`.

This is equivalent to `MOI.get(sampler, FinalNumberOfReads())` for samplers
generated by [`QUBODrivers.@setup`](@ref). If `"final_num_reads"` is unset, the
returned value falls back to raw `"num_reads"` when supported; otherwise it is
`nothing`.
"""
function final_number_of_reads(sampler::AbstractSampler)
    attr = _RawFinalNumberOfReads()
    final_reads = try
        MOI.get(sampler, attr)
    catch err
        _is_unavailable_raw_attr(err, attr) ? nothing : rethrow()
    end

    if isnothing(final_reads)
        return _default_number_of_reads(sampler)
    else
        return final_reads
    end
end

function _is_unavailable_raw_attr(err, attr::RawSamplerAttribute)
    return err isa MOI.GetAttributeNotAllowed{typeof(attr)}
end

function _default_number_of_reads(sampler::AbstractSampler)
    attr = _RawNumberOfReads()

    try
        MOI.supports(sampler, attr) || return nothing

        return MOI.get(sampler, attr)
    catch err
        _is_unavailable_raw_attr(err, attr) ? nothing : rethrow()
    end
end

function _validate_final_number_of_reads(value)
    if !(isnothing(value) || (value isa Integer && value >= zero(value)))
        error(
            "Value for 'FinalNumberOfReads' must be a non-negative integer, " *
            "or 'nothing'",
        )
    end

    return nothing
end

MOIU.map_indices(_, ::FinalNumberOfReads, value) = value
MOIU.map_indices(_, ::_RawFinalNumberOfReads, value) = value
