@doc raw"""
    SamplerAttribute

Abstract supertype for optimizer attributes declared by QUBODrivers samplers.

Attributes generated by [`QUBODrivers.@setup`](@ref), such as
`NumberOfReads`, subtype `SamplerAttribute` and can be used with `MOI.get`,
`MOI.set`, and `MOI.supports`.
"""
abstract type SamplerAttribute <: MOI.AbstractOptimizerAttribute end

@doc raw"""
    RawSamplerAttribute{key}

QUBODrivers raw optimizer attribute identified by a string-like key.

`RawSamplerAttribute("num_reads")` is the QUBODrivers counterpart of
`MOI.RawOptimizerAttribute("num_reads")`. Generated samplers route MOI raw
attributes through this type so solver-specific attributes can share the same
storage and validation as typed sampler attributes.
"""
struct RawSamplerAttribute{key} <: SamplerAttribute
    RawSamplerAttribute{key}() where {key} = new{key}()
end

RawSamplerAttribute(key::String) = RawSamplerAttribute{Symbol(key)}()

const _NUMBER_OF_READS_RAW       = "num_reads"
const _RANDOM_SEED_RAW           = "seed"
const _FINAL_NUMBER_OF_READS_RAW = "final_num_reads"
const _POST_SAMPLE_CALLBACK_RAW  = "post_sample_callback"
const _POST_SAMPLE_TRANSFORM_RAW = "post_sample_transform"

const _RawNumberOfReads       = RawSamplerAttribute{Symbol(_NUMBER_OF_READS_RAW)}
const _RawRandomSeed          = RawSamplerAttribute{Symbol(_RANDOM_SEED_RAW)}
const _RawFinalNumberOfReads  = RawSamplerAttribute{Symbol(_FINAL_NUMBER_OF_READS_RAW)}
const _RawPostSampleCallback  = RawSamplerAttribute{Symbol(_POST_SAMPLE_CALLBACK_RAW)}
const _RawPostSampleTransform = RawSamplerAttribute{Symbol(_POST_SAMPLE_TRANSFORM_RAW)}

@doc raw"""
    RandomSeed()

Generic sampler optimizer attribute for a reproducibility seed.

The raw optimizer attribute key is `"seed"`, and the default value is
`nothing`. Generated optimizers support this typed attribute when the driver
declares the raw `"seed"` attribute in its [`QUBODrivers.@setup`](@ref) block.
When a seed is set, QUBODrivers records it under
`metadata["seeds"]["sampler"]` in the emitted `SampleSet`.
"""
struct RandomSeed <: SamplerAttribute end

@doc raw"""
    FinalNumberOfReads()

Generic sampler optimizer attribute for the number of reads used to build the
final emitted `SampleSet`.

`NumberOfReads` remains the convention for reads used by a sampler's internal
search, optimization, or objective evaluations. `FinalNumberOfReads` separates
the number of reads returned to users from those internal evaluations. If the
final read count is unset (`nothing`), the effective final read count defaults
to the sampler's raw `"num_reads"` attribute when that attribute is supported.

Generated optimizers created by [`QUBODrivers.@setup`](@ref) support this
attribute and the raw `"final_num_reads"` key.
"""
struct FinalNumberOfReads <: SamplerAttribute end

@doc raw"""
    PostSampleCallback()

Generic sampler optimizer attribute for a callback applied after backend
sampling and before the final `SampleSet` is attached to the optimizer.

The raw optimizer attribute key is `"post_sample_callback"`. The callback is
called as `callback(sampleset, sampler)`, where `sampleset` is a copy of the raw
backend output and `sampler` is the optimizer/model context. The callback may
mutate the copied sample-set metadata and return `nothing`, or return a
`SampleSet` to replace the emitted samples. Replacing or changing sample
states, values, reads, sense, or domain requires [`PostSampleTransform`](@ref)
to be set to `true`.
"""
struct PostSampleCallback <: SamplerAttribute end

@doc raw"""
    PostSampleTransform()

Generic sampler optimizer attribute controlling whether
[`PostSampleCallback`](@ref) may transform emitted samples.

The raw optimizer attribute key is `"post_sample_transform"`, and the default
value is `false`. When set to `true`, a post-sample callback may return a
replacement `SampleSet`. QUBODrivers records callback metadata and preserves the
raw samples in the emitted solution metadata.
"""
struct PostSampleTransform <: SamplerAttribute end

@doc raw"""
    @raw_attr_str("key")

Create a `RawSamplerAttribute` type for dispatch.

This macro is useful when extending validation for a particular raw attribute:

```julia
function MOI.set(sampler::Optimizer, attr::QUBODrivers.@raw_attr_str("seed"), value)
    QUBODrivers.set_raw_attr!(sampler, attr, value)
    return nothing
end
```
"""
macro raw_attr_str(key::String)
    return :(RawSamplerAttribute{$(esc(QuoteNode(Symbol(key))))})
end

@doc raw"""
    default_raw_attr(sampler, attr)

Return the default value for a raw sampler attribute.

Methods are generated by [`QUBODrivers.@setup`](@ref) for declared attributes.
Sampler implementations may add methods to customize defaults for additional
raw attributes.
"""
function default_raw_attr end

@doc raw"""
    get_raw_attr(sampler, attr)

Return a raw sampler attribute value.

Generated optimizers first look in the sampler's attribute storage and then
fall back to [`default_raw_attr`](@ref). Most users access this through
`MOI.get(sampler, MOI.RawOptimizerAttribute(name))` or a typed attribute.
"""
function get_raw_attr end

@doc raw"""
    set_raw_attr!(sampler, attr, value)

Store a raw sampler attribute value.

Generated optimizers use this hook from `MOI.set`. Sampler implementations can
specialize it, or specialize `MOI.set` for a `RawSamplerAttribute`, to validate
backend-specific options before storing them.
"""
function set_raw_attr! end

@doc raw"""
    random_seed(sampler)

Return the configured sampler seed, or `nothing` when the sampler does not
support the standard seed attribute or no seed is configured.
"""
function random_seed(sampler::AbstractSampler)
    attr = _RawRandomSeed()

    try
        MOI.supports(sampler, attr) || return nothing

        return MOI.get(sampler, attr)
    catch err
        _is_unavailable_raw_attr(err, attr) ? nothing : rethrow()
    end
end

@doc raw"""
    final_number_of_reads(sampler)

Return the effective final read count for `sampler`.

This is equivalent to `MOI.get(sampler, FinalNumberOfReads())` for samplers
generated by [`QUBODrivers.@setup`](@ref). If `"final_num_reads"` is unset, the
returned value falls back to raw `"num_reads"` when supported; otherwise it is
`nothing`.
"""
function final_number_of_reads(sampler::AbstractSampler)
    attr = _RawFinalNumberOfReads()
    final_reads = try
        MOI.get(sampler, attr)
    catch err
        _is_unavailable_raw_attr(err, attr) ? nothing : rethrow()
    end

    if isnothing(final_reads)
        return _default_number_of_reads(sampler)
    else
        return final_reads
    end
end

@doc raw"""
    post_sample_callback(sampler)

Return the configured post-sample callback for `sampler`, or `nothing` when no
callback is configured or the sampler does not support the generic callback
attribute.
"""
function post_sample_callback(sampler::AbstractSampler)
    attr = _RawPostSampleCallback()

    try
        return MOI.get(sampler, attr)
    catch err
        _is_unavailable_raw_attr(err, attr) ? nothing : rethrow()
    end
end

@doc raw"""
    post_sample_transform(sampler)::Bool

Return whether the configured post-sample callback may transform emitted sample
states, values, reads, sense, or domain. Samplers that do not support the
generic transform attribute default to `false`.
"""
function post_sample_transform(sampler::AbstractSampler)::Bool
    attr = _RawPostSampleTransform()

    transform = try
        MOI.get(sampler, attr)
    catch err
        _is_unavailable_raw_attr(err, attr) ? false : rethrow()
    end

    return transform::Bool
end

@doc raw"""
    total_time(sampleset_or_sampler)

Return `metadata["time"]["total"]`, the wall-clock seconds measured around the
QUBODrivers sampling pipeline, or `nothing` when it is not available.
"""
total_time(sampleset::SampleSet) = _metadata_time(sampleset, "total")
total_time(sampler::AbstractSampler) = total_time(QUBOTools.solution(sampler))

@doc raw"""
    effective_time(sampleset_or_sampler)

Return `metadata["time"]["effective"]`, the backend solve/sampling seconds
reported by the driver, or `nothing` when it is not available.
"""
effective_time(sampleset::SampleSet) = _metadata_time(sampleset, "effective")
effective_time(sampler::AbstractSampler) = effective_time(QUBOTools.solution(sampler))

@doc raw"""
    supports_seed(sampler_or_type)::Bool

Return whether a sampler advertises support for the standard
[`RandomSeed`](@ref) attribute.
"""
supports_seed(::Type{<:AbstractSampler}) = false
supports_seed(sampler::AbstractSampler) = supports_seed(typeof(sampler))

@doc raw"""
    honors_final_reads(sampler_or_type)::Bool

Return whether a sampler uses [`FinalNumberOfReads`](@ref) to control the
number of samples emitted in the final `SampleSet`.
"""
honors_final_reads(::Type{<:AbstractSampler}) = false
honors_final_reads(sampler::AbstractSampler) = honors_final_reads(typeof(sampler))

@doc raw"""
    enforces_time_limit(sampler_or_type)::Bool

Return whether a sampler enforces `MOI.TimeLimitSec()` as part of its own
sampling contract. The default is conservative because many wrappers only store
or forward the attribute.
"""
enforces_time_limit(::Type{<:AbstractSampler}) = false
enforces_time_limit(sampler::AbstractSampler) = enforces_time_limit(typeof(sampler))

function _metadata_time(sampleset::SampleSet, key::String)
    metadata = QUBOTools.metadata(sampleset)
    time = get(metadata, "time", nothing)

    time isa AbstractDict || return nothing

    return get(time, key, nothing)
end

function _is_unavailable_raw_attr(err, attr::RawSamplerAttribute)
    return err isa MOI.GetAttributeNotAllowed{typeof(attr)}
end

function _default_number_of_reads(sampler::AbstractSampler)
    attr = _RawNumberOfReads()

    try
        MOI.supports(sampler, attr) || return nothing

        return MOI.get(sampler, attr)
    catch err
        _is_unavailable_raw_attr(err, attr) ? nothing : rethrow()
    end
end

function _validate_random_seed(value)
    if !(isnothing(value) || (value isa Integer && value >= zero(value)))
        error("Value for 'RandomSeed' must be a non-negative integer, or 'nothing'")
    end

    return nothing
end

function _validate_final_number_of_reads(value)
    if !(isnothing(value) || (value isa Integer && value >= zero(value)))
        error(
            "Value for 'FinalNumberOfReads' must be a non-negative integer, " *
            "or 'nothing'",
        )
    end

    return nothing
end

function _validate_post_sample_transform(value)
    value isa Bool || error("Value for 'PostSampleTransform' must be a boolean")

    return nothing
end

MOIU.map_indices(_, ::RandomSeed, value) = value
MOIU.map_indices(_, ::_RawRandomSeed, value) = value
MOIU.map_indices(_, ::FinalNumberOfReads, value) = value
MOIU.map_indices(_, ::_RawFinalNumberOfReads, value) = value
MOIU.map_indices(_, ::PostSampleCallback, value) = value
MOIU.map_indices(_, ::_RawPostSampleCallback, value) = value
MOIU.map_indices(_, ::PostSampleTransform, value) = value
MOIU.map_indices(_, ::_RawPostSampleTransform, value) = value
