name: Doc Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  doc-preview-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Delete preview and history
        id: cleanup
        run: |
            git config user.name "Documenter.jl"
            git config user.email "documenter@juliadocs.github.io"
            git rm -rf --ignore-unmatch "previews/PR$PRNUM"
            if git diff --cached --quiet; then
                echo "deleted=false" >> "$GITHUB_OUTPUT"
                exit 0
            fi
            git commit -m "delete preview"
            git branch gh-pages-new $(echo "delete history" | git commit-tree HEAD^{tree})
            echo "deleted=true" >> "$GITHUB_OUTPUT"
        env:
            PRNUM: ${{ github.event.number }}

      - name: Push changes
        if: steps.cleanup.outputs.deleted == 'true'
        run: |
            git push --force origin gh-pages-new:gh-pages
# Workflow copied from https://github.com/CliMA/TimeMachine.jl
