name: Doc Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  doc-preview-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: repo

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Delete preview and history
        id: cleanup
        working-directory: gh-pages
        run: bash ../repo/scripts/doc_preview_cleanup.sh
        env:
            PRNUM: ${{ github.event.number }}

      - name: Push changes
        if: steps.cleanup.outputs.deleted == 'true'
        working-directory: gh-pages
        run: git push --force origin gh-pages-new:gh-pages
# Workflow copied from https://github.com/CliMA/TimeMachine.jl
